/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package front;

import controlador.beneficio.ProyeccionBNO;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.BeneficiosBean;
import util.FuncionesUtiles;

/**
 *
 * @author b586854
 */
public class Beneficio extends javax.swing.JFrame {
ArrayList<BeneficiosBean> _matrixBeneficio = null;
    /**
     * Creates new form Ventas
     */
    public Beneficio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTituloDatosBeneficio = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelBnoVentas = new javax.swing.JLabel();
        fechaUno = new javax.swing.JTextField();
        bnoVentasUno = new javax.swing.JTextField();
        fechaDos = new javax.swing.JTextField();
        bnoVentasDos = new javax.swing.JTextField();
        fechaTres = new javax.swing.JTextField();
        bnoVentasTres = new javax.swing.JTextField();
        jButtonCalcularBnoConservador = new javax.swing.JButton();
        jButtonCalcularBnoModerado = new javax.swing.JButton();
        jButtonSolicitud = new javax.swing.JButton();
        jButtonDeudas = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonVentas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        _VGastos1 = new javax.swing.JTextField();
        _VGastos2 = new javax.swing.JTextField();
        _VGastos3 = new javax.swing.JTextField();
        _VCostos1 = new javax.swing.JTextField();
        _VCostos2 = new javax.swing.JTextField();
        _VCostos3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        _MaxBNO = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Beneficio");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        jLabelTituloDatosBeneficio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTituloDatosBeneficio.setText("Datos Beneficio");

        jLabelFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFecha.setText("Fecha");

        jLabelBnoVentas.setText("% BnoVentas");

        fechaUno.setEditable(false);
        fechaUno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fechaUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaUnoActionPerformed(evt);
            }
        });

        bnoVentasUno.setEditable(false);
        bnoVentasUno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        fechaDos.setEditable(false);
        fechaDos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        bnoVentasDos.setEditable(false);
        bnoVentasDos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        fechaTres.setEditable(false);
        fechaTres.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        bnoVentasTres.setEditable(false);
        bnoVentasTres.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButtonCalcularBnoConservador.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonCalcularBnoConservador.setText("Calcular Bno Conservador");
        jButtonCalcularBnoConservador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularBnoConservadorActionPerformed(evt);
            }
        });

        jButtonCalcularBnoModerado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonCalcularBnoModerado.setText("Calcular Bno Moderado");
        jButtonCalcularBnoModerado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularBnoModeradoActionPerformed(evt);
            }
        });

        jButtonSolicitud.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSolicitud.setText("Solicitud");
        jButtonSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolicitudActionPerformed(evt);
            }
        });

        jButtonDeudas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonDeudas.setText("Deudas");
        jButtonDeudas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeudasActionPerformed(evt);
            }
        });

        jButtonSalir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonVentas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonVentas.setText("Ventas");
        jButtonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVentasActionPerformed(evt);
            }
        });

        jLabel1.setText("%Gastos");

        jLabel2.setText("%Costos");

        _VGastos1.setEditable(false);
        _VGastos1.setName(""); // NOI18N

        _VGastos2.setEditable(false);

        _VGastos3.setEditable(false);

        _VCostos1.setEditable(false);

        _VCostos2.setEditable(false);

        _VCostos3.setEditable(false);

        jLabel3.setText("Max %BNO permitido");

        _MaxBNO.setText("30");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelBnoVentas)
                                            .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonCalcularBnoConservador, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonCalcularBnoModerado, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(_VCostos1)
                                            .addComponent(_VGastos1)
                                            .addComponent(bnoVentasUno, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                            .addComponent(fechaUno))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(fechaDos, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(bnoVentasDos, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                                    .addComponent(_VGastos2)
                                                    .addComponent(_VCostos2))))
                                        .addGap(69, 69, 69)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDeudas, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_MaxBNO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTituloDatosBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 521, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(_VCostos3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(fechaTres, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(bnoVentasTres, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(_VGastos3))
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloDatosBeneficio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(_MaxBNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha)
                    .addComponent(fechaUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBnoVentas)
                    .addComponent(bnoVentasUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnoVentasDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnoVentasTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(_VGastos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_VGastos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_VGastos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(_VCostos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_VCostos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_VCostos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCalcularBnoConservador)
                            .addComponent(jButtonCalcularBnoModerado))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSolicitud)
                            .addComponent(jButtonDeudas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSalir)
                            .addComponent(jButtonVentas))
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String linea;
        String[] datosBeneficio;

        BufferedReader bf = null;
        try {
            bf = new BufferedReader(new FileReader("C:\\PConceptoCapacidad\\archivos\\ArchivoCargaBeneficio.txt"));
            try {
                _matrixBeneficio = new ArrayList<BeneficiosBean>();
                
                while ((linea = bf.readLine()) != null) {//cambiar

                    datosBeneficio = linea.split(",");
                    System.out.println("---"+datosBeneficio[0]);
                    _matrixBeneficio.add(new BeneficiosBean(datosBeneficio[0], datosBeneficio[1], datosBeneficio[2], datosBeneficio[3],datosBeneficio[4],datosBeneficio[5]));
                    
                }


                for (int i = 0; i < _matrixBeneficio.size(); i++) {

                    if (i == 0) {
                        fechaUno.setText(_matrixBeneficio.get(i).getFecha());
                        bnoVentasUno.setText(String.valueOf(_matrixBeneficio.get(i).getBnoVentas()));
                        _VGastos1.setText(String.valueOf(_matrixBeneficio.get(i).getPorcGasto()));
                        _VCostos1.setText(String.valueOf(_matrixBeneficio.get(i).getPorcCostos()));
                    } else if (i == 1) {
                        fechaDos.setText(_matrixBeneficio.get(i).getFecha());
                        bnoVentasDos.setText(String.valueOf(_matrixBeneficio.get(i).getBnoVentas()));
                        _VGastos2.setText(String.valueOf(_matrixBeneficio.get(i).getPorcGasto()));
                        _VCostos2.setText(String.valueOf(_matrixBeneficio.get(i).getPorcCostos()));
                    } else if (i == 2) {
                        fechaTres.setText(_matrixBeneficio.get(i).getFecha());
                        bnoVentasTres.setText(String.valueOf(_matrixBeneficio.get(i).getBnoVentas()));
                        _VGastos3.setText(String.valueOf(_matrixBeneficio.get(i).getPorcGasto()));
                        _VCostos3.setText(String.valueOf(_matrixBeneficio.get(i).getPorcCostos()));
                    }

                }



            } catch (IOException ex) {
                Logger.getLogger(Deudas.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NumberFormatException nb) {
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Deudas.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                bf.close();
            } catch (IOException ex) {
                Logger.getLogger(Deudas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_formWindowOpened

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    /**
     *Llamada al boton que genera el beneficio bajo escenario conservador
     * Llama al metodo Proyectar Beneficio (Parametros -> Matriz de Datos, Indicador del tipo de escenario, macimo beneficio permitido)
     */
    private void jButtonCalcularBnoConservadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularBnoConservadorActionPerformed
       boolean _exito = false;
       int maximoBeneficio = 0;
        ProyeccionBNO _accesoControlador = new ProyeccionBNO();
        maximoBeneficio = (_MaxBNO.getText().isEmpty())?0:Integer.parseInt(_MaxBNO.getText());
       _exito = _accesoControlador.ProyectarBeneficio(_matrixBeneficio,1,maximoBeneficio);//
       if(_exito == true)
           JOptionPane.showMessageDialog(null, "Archivo Generado Exitosamente");
       else
           JOptionPane.showMessageDialog(new JFrame(), "Error generando el archivo", "Dialog", JOptionPane.ERROR_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCalcularBnoConservadorActionPerformed

    private void jButtonSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolicitudActionPerformed
        if (FuncionesUtiles.isVacio(fechaUno.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha primera no puede  ser vacia");

        } else if (!FuncionesUtiles.isFormatoFecha(fechaUno.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha primera  debe contener el siguiente formato ##/##/####");

        } else if (FuncionesUtiles.isVacio(fechaDos.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha segunda no puede ser vacia");

        } else if (!FuncionesUtiles.isFormatoFecha(fechaDos.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha segunda  debe contener el siguiente formato ##/##/####");

        } else if (FuncionesUtiles.isVacio(fechaTres.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha tercera no puede ser vacia");

        } else if (!FuncionesUtiles.isFormatoFecha(fechaTres.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha tercera  debe contener el siguiente formato ##/##/####");

        } else if (FuncionesUtiles.isVacio(bnoVentasUno.getText())) {
            JOptionPane.showMessageDialog(null, "El Bno Venta Uno no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(bnoVentasUno.getText())) {
            JOptionPane.showMessageDialog(null, "El Bno Ventas uno debe ser númerico");

        } else if (FuncionesUtiles.isVacio(bnoVentasDos.getText())) {
            JOptionPane.showMessageDialog(null, "El Bno Venta Dos no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(bnoVentasDos.getText())) {
            JOptionPane.showMessageDialog(null, "El Bno Ventas Dos debe ser númerico");

        } else if (FuncionesUtiles.isVacio(bnoVentasTres.getText())) {
            JOptionPane.showMessageDialog(null, "El Bno Venta Tres no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(bnoVentasTres.getText())) {
            JOptionPane.showMessageDialog(null, "El Bno Ventas Tres debe ser númerico");

        } else {
            SolicitudArchivo solicitudArchivo = new SolicitudArchivo();
            solicitudArchivo.setLocationRelativeTo(null);
            solicitudArchivo.setVisible(true);
            this.setVisible(false);
        }

    }//GEN-LAST:event_jButtonSolicitudActionPerformed

    private void jButtonDeudasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeudasActionPerformed
        if (FuncionesUtiles.isVacio(fechaUno.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha primera no puedeser vacia");

        } else if (!FuncionesUtiles.isFormatoFecha(fechaUno.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha primera  debe contener el siguiente formato ##/##/####");

        } else if (FuncionesUtiles.isVacio(fechaDos.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha segunda no puedeser vacia");

        } else if (!FuncionesUtiles.isFormatoFecha(fechaDos.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha segunda  debe contener el siguiente formato ##/##/####");

        } else if (FuncionesUtiles.isVacio(fechaTres.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha tercera no puede ser vacia");

        } else if (!FuncionesUtiles.isFormatoFecha(fechaTres.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha tercera  debe contener el siguiente formato ##/##/####");

        } else if (FuncionesUtiles.isVacio(bnoVentasUno.getText())) {
            JOptionPane.showMessageDialog(null, "El Bno Venta Uno no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(bnoVentasUno.getText())) {
            JOptionPane.showMessageDialog(null, "El Bno Ventas Dos debe ser númerico");

        } else if (FuncionesUtiles.isVacio(bnoVentasDos.getText())) {
            JOptionPane.showMessageDialog(null, "El Bno Venta Dos no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(bnoVentasDos.getText())) {
            JOptionPane.showMessageDialog(null, "El Bno Ventas Dos debe ser númerico");

        } else if (FuncionesUtiles.isVacio(bnoVentasTres.getText())) {
            JOptionPane.showMessageDialog(null, "El Bno Venta Tres no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(bnoVentasTres.getText())) {
            JOptionPane.showMessageDialog(null, "El Bno Ventas Tres debe ser númerico");

        } else {
            Deudas deudas = new Deudas();
            deudas.setLocationRelativeTo(null);
            deudas.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonDeudasActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVentasActionPerformed
        if (FuncionesUtiles.isVacio(fechaUno.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha primera puede ser vacia");

        } else if (!FuncionesUtiles.isFormatoFecha(fechaUno.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha primera  debe contener el siguiente formato ##/##/####");

        } else if (FuncionesUtiles.isVacio(fechaDos.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha segunda puede ser vacia");

        } else if (!FuncionesUtiles.isFormatoFecha(fechaDos.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha segunda  debe contener el siguiente formato ##/##/####");

        } else if (FuncionesUtiles.isVacio(fechaTres.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha tercera puede ser vacia");

        } else if (!FuncionesUtiles.isFormatoFecha(fechaTres.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha tercera  debe contener el siguiente formato ##/##/####");

        } else if (FuncionesUtiles.isVacio(bnoVentasUno.getText())) {
            JOptionPane.showMessageDialog(null, "El Bno Venta Uno puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(bnoVentasUno.getText())) {
            JOptionPane.showMessageDialog(null, "El Bno Ventas Dos debe ser númerico");

        } else if (FuncionesUtiles.isVacio(bnoVentasDos.getText())) {
            JOptionPane.showMessageDialog(null, "El Bno Venta Dos puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(bnoVentasDos.getText())) {
            JOptionPane.showMessageDialog(null, "El Bno Ventas Dos debe ser númerico");

        } else if (FuncionesUtiles.isVacio(bnoVentasTres.getText())) {
            JOptionPane.showMessageDialog(null, "El Bno Venta Tres puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(bnoVentasTres.getText())) {
            JOptionPane.showMessageDialog(null, "El Bno Ventas Tres debe ser númerico");

        } else {
            Ventas ventas = new Ventas();
            ventas.setLocationRelativeTo(null);
            ventas.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonVentasActionPerformed

    private void fechaUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaUnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaUnoActionPerformed

    private void jButtonCalcularBnoModeradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularBnoModeradoActionPerformed
        int maximoBeneficio = 0;
        boolean _exito = false;
        ProyeccionBNO _accesoControlador = new ProyeccionBNO();
        maximoBeneficio = (_MaxBNO.getText().isEmpty())?0:Integer.parseInt(_MaxBNO.getText());
        /**
         *Boton de accion Calcula del Beneficio Moderado
         */
        if(maximoBeneficio == 0)
        {
          JOptionPane.showMessageDialog(new JFrame(), "Maximo BNO esta vacío", "Dialog", JOptionPane.ERROR_MESSAGE);  
        }else{ 
            
            _exito = _accesoControlador.ProyectarBeneficio(_matrixBeneficio,2,maximoBeneficio);
            if (_exito == true) {
                JOptionPane.showMessageDialog(null, "Archivo Generado Exitosamente");
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "Error generando el archivo", "Dialog", JOptionPane.ERROR_MESSAGE);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCalcularBnoModeradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beneficio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beneficio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beneficio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beneficio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beneficio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField _MaxBNO;
    public static javax.swing.JTextField _VCostos1;
    public static javax.swing.JTextField _VCostos2;
    public static javax.swing.JTextField _VCostos3;
    public static javax.swing.JTextField _VGastos1;
    public static javax.swing.JTextField _VGastos2;
    public static javax.swing.JTextField _VGastos3;
    private javax.swing.JTextField bnoVentasDos;
    private javax.swing.JTextField bnoVentasTres;
    private javax.swing.JTextField bnoVentasUno;
    private javax.swing.JTextField fechaDos;
    private javax.swing.JTextField fechaTres;
    private javax.swing.JTextField fechaUno;
    private javax.swing.JButton jButtonCalcularBnoConservador;
    private javax.swing.JButton jButtonCalcularBnoModerado;
    private javax.swing.JButton jButtonDeudas;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSolicitud;
    private javax.swing.JButton jButtonVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBnoVentas;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelTituloDatosBeneficio;
    // End of variables declaration//GEN-END:variables
}
