/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package front;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.VentasBean;
import util.FuncionesUtiles;

/**
 *
 * @author b586854
 */
public class Ventas extends javax.swing.JFrame {

    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDatosVentas = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelMeses = new javax.swing.JLabel();
        jLabelVentasNetas = new javax.swing.JLabel();
        jLabelVarVentas = new javax.swing.JLabel();
        fechaUno = new javax.swing.JTextField();
        mesesUno = new javax.swing.JTextField();
        ventasUno = new javax.swing.JTextField();
        varVentasUno = new javax.swing.JTextField();
        fechaDos = new javax.swing.JTextField();
        mesesDos = new javax.swing.JTextField();
        ventasDos = new javax.swing.JTextField();
        varVentasDos = new javax.swing.JTextField();
        fechaTres = new javax.swing.JTextField();
        mesesTres = new javax.swing.JTextField();
        ventasTres = new javax.swing.JTextField();
        varVentasTres = new javax.swing.JTextField();
        jButtonCalcularVentasConservador = new javax.swing.JButton();
        jButtonCalcularVentasModerado = new javax.swing.JButton();
        jButtonSolicitud = new javax.swing.JButton();
        jButtonBeneficio = new javax.swing.JButton();
        jButtonDeudas = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabelDatosVentas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDatosVentas.setText("Datos Ventas");

        jLabelFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFecha.setText("Fecha");

        jLabelMeses.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMeses.setText("Meses");

        jLabelVentasNetas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelVentasNetas.setText("VentasNetas");

        jLabelVarVentas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelVarVentas.setText("% VarVentas");

        fechaUno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        mesesUno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        ventasUno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        varVentasUno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        fechaDos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        mesesDos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        ventasDos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        varVentasDos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        fechaTres.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        mesesTres.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        ventasTres.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        varVentasTres.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButtonCalcularVentasConservador.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonCalcularVentasConservador.setText("Calcular Ventas Conservador");

        jButtonCalcularVentasModerado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonCalcularVentasModerado.setText("Calcular Ventas Moderado");

        jButtonSolicitud.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSolicitud.setText("Solicitud");
        jButtonSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolicitudActionPerformed(evt);
            }
        });

        jButtonBeneficio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonBeneficio.setText("Beneficio");
        jButtonBeneficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBeneficioActionPerformed(evt);
            }
        });

        jButtonDeudas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonDeudas.setText("Deudas");
        jButtonDeudas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeudasActionPerformed(evt);
            }
        });

        jButtonSalir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDatosVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButtonBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jLabelFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabelMeses, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabelVentasNetas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabelVarVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(mesesUno)
                                                    .addComponent(ventasUno)
                                                    .addComponent(varVentasUno)
                                                    .addComponent(fechaUno, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 24, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jButtonCalcularVentasConservador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jButtonCalcularVentasModerado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(45, 45, 45)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(ventasDos, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(mesesDos, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(fechaDos, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(varVentasDos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(56, 56, 56)
                                                .addComponent(jButtonSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(mesesTres, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addComponent(fechaTres)
                                .addComponent(ventasTres)
                                .addComponent(varVentasTres))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jButtonDeudas, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDatosVentas)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha)
                    .addComponent(fechaUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMeses)
                    .addComponent(mesesUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesesDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesesTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ventasTres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelVentasNetas)
                        .addComponent(ventasUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ventasDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelVarVentas)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(varVentasUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(varVentasDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(varVentasTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCalcularVentasConservador)
                    .addComponent(jButtonSolicitud)
                    .addComponent(jButtonDeudas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCalcularVentasModerado)
                    .addComponent(jButtonBeneficio)
                    .addComponent(jButtonSalir))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        String linea;
        String[] datosVentas;
        ArrayList<VentasBean> _matrixVentas = null;
        BufferedReader bf = null;
        try {
            bf = new BufferedReader(new FileReader("C:\\PConceptoCapacidad\\archivos\\ArchivoCargaVentas.txt"));
            try {
                _matrixVentas = new ArrayList<VentasBean>();
                int secuencia = 0;

                while ((linea = bf.readLine()) != null) {

                    datosVentas = linea.split(",");
                    _matrixVentas.add(new VentasBean(secuencia, datosVentas[0], datosVentas[1], datosVentas[2], datosVentas[3], datosVentas[4]));
                    secuencia++;
                }
           
                for (int i = 0; i < _matrixVentas.size(); i++) {

                    if (i == 0) {
                        fechaUno.setText(_matrixVentas.get(i).getFecha());
                        mesesUno.setText(String.valueOf(_matrixVentas.get(i).getMeses()));
                        ventasUno.setText(FuncionesUtiles.formatoDouble(_matrixVentas.get(i).getVentasNetas()));
                        varVentasUno.setText(String.valueOf(_matrixVentas.get(i).getVarVentas()));
                    } else if (i == 1) {
                        fechaDos.setText(_matrixVentas.get(i).getFecha());
                        mesesDos.setText(String.valueOf(_matrixVentas.get(i).getMeses()));
                        ventasDos.setText(FuncionesUtiles.formatoDouble(_matrixVentas.get(i).getVentasNetas()));
                        varVentasDos.setText(String.valueOf(_matrixVentas.get(i).getVarVentas()));
                    } else  if (i == 2) {
                        fechaTres.setText(_matrixVentas.get(i).getFecha());
                        mesesTres.setText(String.valueOf(_matrixVentas.get(i).getMeses()));
                        ventasTres.setText(FuncionesUtiles.formatoDouble(_matrixVentas.get(i).getVentasNetas()));
                        varVentasTres.setText(String.valueOf(_matrixVentas.get(i).getVarVentas()));
                    }

                }
                
                 Collections.sort(_matrixVentas);
                 for (int i = 0; i < _matrixVentas.size(); i++) {
                    System.out.println("front.Beneficio.formWindowOpened()"+_matrixVentas.get(i).getVentasNetas());
                }
                  

            } catch (IOException ex) {
                Logger.getLogger(Deudas.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NumberFormatException nb) {
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Deudas.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                bf.close();
            } catch (IOException ex) {
                Logger.getLogger(Deudas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_formWindowOpened

    private void jButtonSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolicitudActionPerformed
        if (FuncionesUtiles.isVacio(fechaUno.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha primera puede ser vacia");

        } else if (!FuncionesUtiles.isFormatoFecha(fechaUno.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha primera  debe contener el siguiente formato ##/##/####");

        } else if (FuncionesUtiles.isVacio(fechaDos.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha segunda puede ser vacia");

        } else if (!FuncionesUtiles.isFormatoFecha(fechaDos.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha segunda  debe contener el siguiente formato ##/##/####");

        } else if (FuncionesUtiles.isVacio(fechaTres.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha tercera puede ser vacia");

        } else if (!FuncionesUtiles.isFormatoFecha(fechaTres.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha tercera  debe contener el siguiente formato ##/##/####");

        } else if (FuncionesUtiles.isVacio(mesesUno.getText())) {
            JOptionPane.showMessageDialog(null, "El mes primero no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(mesesUno.getText())) {
            JOptionPane.showMessageDialog(null, "El mes Primero debe ser númerico");

        } else if (FuncionesUtiles.isVacio(mesesDos.getText())) {
            JOptionPane.showMessageDialog(null, "El mes segundo  no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(mesesDos.getText())) {
            JOptionPane.showMessageDialog(null, "El mes segundo   debe ser númerico");

        } else if (FuncionesUtiles.isVacio(mesesTres.getText())) {
            JOptionPane.showMessageDialog(null, "El meses tercero no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(mesesTres.getText())) {
            JOptionPane.showMessageDialog(null, "El meses tercero debe ser númerico");

        } else if (FuncionesUtiles.isVacio(ventasUno.getText())) {
            JOptionPane.showMessageDialog(null, "La ventas netas primera no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(ventasUno.getText())) {
            JOptionPane.showMessageDialog(null, "La ventas netas primera debe ser númerico");

        } else if (FuncionesUtiles.isVacio(ventasDos.getText())) {
            JOptionPane.showMessageDialog(null, "La ventas netas segunda no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(ventasDos.getText())) {
            JOptionPane.showMessageDialog(null, "La ventas netas segundas debe ser númerico");

        } else if (FuncionesUtiles.isVacio(ventasTres.getText())) {
            JOptionPane.showMessageDialog(null, "La ventas netas tercera no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(ventasTres.getText())) {
            JOptionPane.showMessageDialog(null, "La ventas netas tercera debe ser númerico");

        } else if (FuncionesUtiles.isVacio(varVentasUno.getText())) {
            JOptionPane.showMessageDialog(null, "La variacion de ventas  primera no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(varVentasUno.getText())) {
            JOptionPane.showMessageDialog(null, "La variacion de ventas  primera debe ser númerico");

        } else if (FuncionesUtiles.isVacio(varVentasDos.getText())) {
            JOptionPane.showMessageDialog(null, "La variacion de ventas  Segunda no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(varVentasDos.getText())) {
            JOptionPane.showMessageDialog(null, "La variacion de ventas Segunda debe ser númerico");

        } else if (FuncionesUtiles.isVacio(varVentasTres.getText())) {
            JOptionPane.showMessageDialog(null, "La variacion de ventas  Tercera no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(varVentasTres.getText())) {
            JOptionPane.showMessageDialog(null, "La variacion de ventas tercera debe ser númerico");

        } else {
            SolicitudArchivo solicitudArchivo = new SolicitudArchivo();

            solicitudArchivo.setLocationRelativeTo(null);
            solicitudArchivo.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonSolicitudActionPerformed

    private void jButtonDeudasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeudasActionPerformed
        if (FuncionesUtiles.isVacio(fechaUno.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha primera puede ser vacia");

        } else if (!FuncionesUtiles.isFormatoFecha(fechaUno.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha primera  debe contener el siguiente formato ##/##/####");

        } else if (FuncionesUtiles.isVacio(fechaDos.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha segunda puede ser vacia");

        } else if (!FuncionesUtiles.isFormatoFecha(fechaDos.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha segunda  debe contener el siguiente formato ##/##/####");

        } else if (FuncionesUtiles.isVacio(fechaTres.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha tercera puede ser vacia");

        } else if (!FuncionesUtiles.isFormatoFecha(fechaTres.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha tercera  debe contener el siguiente formato ##/##/####");

        } else if (FuncionesUtiles.isVacio(mesesUno.getText())) {
            JOptionPane.showMessageDialog(null, "El mes primero no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(mesesUno.getText())) {
            JOptionPane.showMessageDialog(null, "El mes Primero debe ser númerico");

        } else if (FuncionesUtiles.isVacio(mesesDos.getText())) {
            JOptionPane.showMessageDialog(null, "El mes segundo  no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(mesesDos.getText())) {
            JOptionPane.showMessageDialog(null, "El mes segundo   debe ser númerico");

        } else if (FuncionesUtiles.isVacio(mesesTres.getText())) {
            JOptionPane.showMessageDialog(null, "El meses tercero no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(mesesTres.getText())) {
            JOptionPane.showMessageDialog(null, "El meses tercero debe ser númerico");

        } else if (FuncionesUtiles.isVacio(ventasUno.getText())) {
            JOptionPane.showMessageDialog(null, "La ventas netas primera no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(ventasUno.getText())) {
            JOptionPane.showMessageDialog(null, "La ventas netas primera debe ser númerico");

        } else if (FuncionesUtiles.isVacio(ventasDos.getText())) {
            JOptionPane.showMessageDialog(null, "La ventas netas segunda no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(ventasDos.getText())) {
            JOptionPane.showMessageDialog(null, "La ventas netas segundas debe ser númerico");

        } else if (FuncionesUtiles.isVacio(ventasTres.getText())) {
            JOptionPane.showMessageDialog(null, "La ventas netas tercera no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(ventasTres.getText())) {
            JOptionPane.showMessageDialog(null, "La ventas netas tercera debe ser númerico");

        } else if (FuncionesUtiles.isVacio(varVentasUno.getText())) {
            JOptionPane.showMessageDialog(null, "La variacion de ventas  primera no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(varVentasUno.getText())) {
            JOptionPane.showMessageDialog(null, "La variacion de ventas  primera debe ser númerico");

        } else if (FuncionesUtiles.isVacio(varVentasDos.getText())) {
            JOptionPane.showMessageDialog(null, "La variacion de ventas  Segunda no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(varVentasDos.getText())) {
            JOptionPane.showMessageDialog(null, "La variacion de ventas Segunda debe ser númerico");

        } else if (FuncionesUtiles.isVacio(varVentasTres.getText())) {
            JOptionPane.showMessageDialog(null, "La variacion de ventas  Tercera no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(varVentasTres.getText())) {
            JOptionPane.showMessageDialog(null, "La variacion de ventas tercera debe ser númerico");

        } else {
            Deudas deudas = new Deudas();
            deudas.setLocationRelativeTo(null);
            deudas.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonDeudasActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonBeneficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBeneficioActionPerformed
        if (FuncionesUtiles.isVacio(fechaUno.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha primera puede ser vacia");

        } else if (!FuncionesUtiles.isFormatoFecha(fechaUno.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha primera  debe contener el siguiente formato ##/##/####");

        } else if (FuncionesUtiles.isVacio(fechaDos.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha segunda puede ser vacia");

        } else if (!FuncionesUtiles.isFormatoFecha(fechaDos.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha segunda  debe contener el siguiente formato ##/##/####");

        } else if (FuncionesUtiles.isVacio(fechaTres.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha tercera puede ser vacia");

        } else if (!FuncionesUtiles.isFormatoFecha(fechaTres.getText())) {
            JOptionPane.showMessageDialog(null, "La fecha tercera  debe contener el siguiente formato ##/##/####");

        } else if (FuncionesUtiles.isVacio(mesesUno.getText())) {
            JOptionPane.showMessageDialog(null, "El mes primero no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(mesesUno.getText())) {
            JOptionPane.showMessageDialog(null, "El mes Primero debe ser númerico");

        } else if (FuncionesUtiles.isVacio(mesesDos.getText())) {
            JOptionPane.showMessageDialog(null, "El mes segundo  no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(mesesDos.getText())) {
            JOptionPane.showMessageDialog(null, "El mes segundo   debe ser númerico");

        } else if (FuncionesUtiles.isVacio(mesesTres.getText())) {
            JOptionPane.showMessageDialog(null, "El meses tercero no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(mesesTres.getText())) {
            JOptionPane.showMessageDialog(null, "El meses tercero debe ser númerico");

        } else if (FuncionesUtiles.isVacio(ventasUno.getText())) {
            JOptionPane.showMessageDialog(null, "La ventas netas primera no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(ventasUno.getText())) {
            JOptionPane.showMessageDialog(null, "La ventas netas primera debe ser númerico");

        } else if (FuncionesUtiles.isVacio(ventasDos.getText())) {
            JOptionPane.showMessageDialog(null, "La ventas netas segunda no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(ventasDos.getText())) {
            JOptionPane.showMessageDialog(null, "La ventas netas segundas debe ser númerico");

        } else if (FuncionesUtiles.isVacio(ventasTres.getText())) {
            JOptionPane.showMessageDialog(null, "La ventas netas tercera no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(ventasTres.getText())) {
            JOptionPane.showMessageDialog(null, "La ventas netas tercera debe ser númerico");

        } else if (FuncionesUtiles.isVacio(varVentasUno.getText())) {
            JOptionPane.showMessageDialog(null, "La variacion de ventas  primera no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(varVentasUno.getText())) {
            JOptionPane.showMessageDialog(null, "La variacion de ventas  primera debe ser númerico");

        } else if (FuncionesUtiles.isVacio(varVentasDos.getText())) {
            JOptionPane.showMessageDialog(null, "La variacion de ventas  Segunda no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(varVentasDos.getText())) {
            JOptionPane.showMessageDialog(null, "La variacion de ventas Segunda debe ser númerico");

        } else if (FuncionesUtiles.isVacio(varVentasTres.getText())) {
            JOptionPane.showMessageDialog(null, "La variacion de ventas  Tercera no puede ser vacia");

        } else if (!FuncionesUtiles.isNumerico(varVentasTres.getText())) {
            JOptionPane.showMessageDialog(null, "La variacion de ventas tercera debe ser númerico");

        } else {
            Beneficio beneficios = new Beneficio();
            beneficios.setLocationRelativeTo(null);
            beneficios.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonBeneficioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fechaDos;
    private javax.swing.JTextField fechaTres;
    private javax.swing.JTextField fechaUno;
    private javax.swing.JButton jButtonBeneficio;
    private javax.swing.JButton jButtonCalcularVentasConservador;
    private javax.swing.JButton jButtonCalcularVentasModerado;
    private javax.swing.JButton jButtonDeudas;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSolicitud;
    private javax.swing.JLabel jLabelDatosVentas;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelMeses;
    private javax.swing.JLabel jLabelVarVentas;
    private javax.swing.JLabel jLabelVentasNetas;
    private javax.swing.JTextField mesesDos;
    private javax.swing.JTextField mesesTres;
    private javax.swing.JTextField mesesUno;
    private javax.swing.JTextField varVentasDos;
    private javax.swing.JTextField varVentasTres;
    private javax.swing.JTextField varVentasUno;
    private javax.swing.JTextField ventasDos;
    private javax.swing.JTextField ventasTres;
    private javax.swing.JTextField ventasUno;
    // End of variables declaration//GEN-END:variables
}
